#!/bin/bash
docker run --name Abathur -dt  -v ~/Abathur:/root/ -p 3000:3000 python:2-slim bash
docker exec Abathur pip install Flask
docker exec --env FLASK_APP=hello Abathur flask run --host=0.0.0.0 --port=3000
